contexts:
  daisychain:
    repo_root: code/daisychain
    gitconfig_path: ~/.gitconfig-daisychain
    gcloud_config: daisychain
  other_projects:
    repo_root: code/personal
    gitconfig_path: ~/.gitconfig-other-projects
  proxima:
    repo_root: code/proxima
    gitconfig_path: ~/.gitconfig-proxima
    gcloud_config: proxima

profiles:
  meta_mac:
    machine_role: meta
    selector:
      os: darwin
      usernames:
        - fxbc
      hostnames: []
    enabled_contexts:
      - daisychain
      - other_projects
      - proxima
  DC_OS:
    machine_role: daisychain
    selector:
      os: darwin
      usernames:
        - DC
      hostnames: []
    enabled_contexts:
      - daisychain
  XA_OS:
    machine_role: other_projects
    selector:
      os: darwin
      usernames:
        - XA
      hostnames: []
    enabled_contexts:
      - other_projects
      - proxima
  fx_linux:
    machine_role: linux_execution
    selector:
      os: linux
      usernames:
        - xavier
      hostnames:
        - fx
    enabled_contexts:
      - daisychain
      - other_projects
      - proxima
