contexts:
  daisychain:
    repo_root: code/daisychain
    gcloud_config: daisychain
  other_projects:
    repo_root: code/personal
  proxima:
    repo_root: code/proxima
    gcloud_config: proxima

profiles:
  meta_mac:
    machine_role: meta
    selector:
      os: darwin
      usernames:
        - fxbc
      hostnames: []
  DC_OS:
    machine_role: daisychain
    selector:
      os: darwin
      usernames:
        - DC
      hostnames: []
  XA_OS:
    machine_role: other_projects
    selector:
      os: darwin
      usernames:
        - XA
      hostnames: []
  fx_linux:
    machine_role: linux_execution
    selector:
      os: linux
      usernames:
        - xavier
      hostnames:
        - fx
